### ISSUE TITLE
Cannot observe color value on paper-color-circle

### ISSUE THREAD

**Issue by balloob** [David-Mulder/paper-color-picker#14]
I am unable to easily observe the color value from a paper-color-circle. In the following example, `colorChanged` will never be called.

``` html
<paper-color-circle shape='square' value='{{color}}'></paper-color-circle>
```

``` javascript
attributes: {
  color: {
    type: Object,
    observer: 'colorChanged',
  }
}
```

I can add an observer on the properties. It works, but it will be called three times with one property each time.

``` javascript
  observers: [
    'colorChanged(color.*)',
  ],
```

Because of the [order of `set` calls](https://github.com/David-Mulder/paper-color-picker/blob/master/paper-color-circle.html#L300), I can listen for `color.blue` and refer to `this.color` to get the latest color. Is this the preferred approach?

**Comment by David-Mulder** [comment]
Observing objects in Polymer always is like that, Technically the object itself isn't changing, so you have to listen to the things that do change. Yeah, it's a pain in the **\* sometimes, but it seems you have figured it out. You can then either listen for specific path changes indeed and handle them 1 by 1, or just debounce the entire thing. Not sure which is more beautiful from an aesthetic point of view.
