### ISSUE TITLE
demo.html not working

### ISSUE THREAD

**Issue by kirlen** [David-Mulder/paper-color-picker#3]
Hi. Trying to use your cool component. When I run demo.html, I get

Uncaught TypeError: prototype.registerCallback is not a function - polymer-micro.html:73

I'm using polymer 1.x and the Polymer Starter Kit. Is it supported? Thanks!

**Comment by David-Mulder** [comment]
@kirlen Check the README first line :wink: But on the upside, I am working with Polymer full time lately again, so I am really hoping to get to it :smile:

**Comment by kirlen** [comment]
not sure what you're referring to in the README, but thanks for the update!

**Comment by David-Mulder** [comment]
@kirlen SORRY, didn't notice that this was the paper-color-picker and not my paper-date-picker. Yeah, I need to update both of them, though I have to be honest the date-picker is higher priority.

**Comment by David-Mulder** [comment]
@kirlen It took quite awhile, but it's finally update to Polymer 1.0 and updated to the latest Material Design spec and all that.
