### ISSUE TITLE
Update to Polymer 1.0

### ISSUE THREAD

**Issue by IchordeDionysos** [David-Mulder/paper-color-picker#4]
Cool element, but unluckily in 0.5.

You may want to use [Polyup](http://polymerlabs.github.io/polyup/)

**Comment by David-Mulder** [comment]
@IchordeDionysos Yeah I know I should upgrade, but been terribly busy with a lot of stuff :crying_cat_face: . Not even entirely sure whether I will ever get to it~ but I will definitely accept a properly done pull request for an upgrade :)

**Comment by IchordeDionysos** [comment]
I've updated it!
This element is so cool, you should upload it to bower, like this [Upload to customelements.io](https://customelements.io/#steps) that everyone can find it on [customelements.io](https://customelements.io)
